apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  containers:
    - name: container-mysql
      image: mysql/mysql-server:5.7
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "1234"
        - name: MYSQL_DATABASE
          value: "tasker_database"
        - name: MYSQL_USER
          value: "app_user"
        - name: MYSQL_PASSWORD
          value: "1234"
